In [136]:
import numpy as np
import tensorflow as tf


In [147]:
a = tf.truncated_normal([2,3], 1.0, 0.001)
c = tf.constant([1,2,3],dtype=tf.float32)

In [148]:
print(a)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    b = sess.run(a)
#     b = a.eval()
    print(b)
    print(c.eval())

Tensor("truncated_normal_16:0", shape=(2, 3), dtype=float32)
[[0.99861676 0.9999932  1.0003835 ]
 [0.9998409  1.0005143  0.99973994]]
[1. 2. 3.]


In [166]:
prob_total = np.random.random((0, 5))
print(prob_total)
# prob_total = [[1,2,3,4]]
prob_total = np.concatenate((prob_total, [[1,2,3,4,5,6]]), axis=0)
# print(prob_total.shape)
print(prob_total)

[]


ValueError: all the input arrays must have same number of dimensions

In [168]:
with tf.Session() as sess:    
    label = tf.one_hot([1,2,1,0], on_value=1, off_value=0, depth=4)
    _label = sess.run(label)
    print(_label)
    print()
#     print(list(_label))

[[0 1 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]



In [153]:
a = np.array([2,3,4])
print(a.shape)

(3,)


In [154]:
a = [2,3,4]
print(a.shape)

AttributeError: 'list' object has no attribute 'shape'